-- =============================================================================
-- V12__sequences_dotnet.sql (variante H2)
-- Equivalente funcional de db/migration-oracle/V12__sequences_dotnet.sql.
-- TASK-25 (DB-01) — Caminho A: cria as 20 sequences do domínio .NET que o EF
-- Core declara via HasDefaultValueSql("SEQ_x.NEXTVAL") e converte as PKs das
-- 20 tabelas .NET-owned de IDENTITY para DEFAULT sequence.
--
-- Mapa completo das 25 tabelas: docs/V12-pk-strategy-map.md
--
-- Diferenças de sintaxe em relação à variante Oracle (só sintaxe — o efeito no
-- schema é o mesmo):
--   Oracle: ALTER TABLE t MODIFY (c DROP IDENTITY)
--   H2    : ALTER TABLE t ALTER COLUMN c DROP IDENTITY
--   Oracle: ALTER TABLE t MODIFY (c DEFAULT SEQ_X.NEXTVAL)
--   H2    : ALTER TABLE t ALTER COLUMN c SET DEFAULT NEXT VALUE FOR SEQ_X
-- `NEXT VALUE FOR` é a forma nativa do H2 (SQL:2003); SEQ_X.NEXTVAL só existe
-- lá via MODE=Oracle e não é aceito em expressão de DEFAULT.
-- =============================================================================

-- ─── 1. Sequences das 9 tabelas .NET-owned nascidas na V1 ────────────────────
CREATE SEQUENCE SEQ_CLINICA        START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ESPECIE        START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TIPO_EVENTO    START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_RACA           START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_VETERINARIO    START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TUTOR          START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PET            START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_INVITE_TUTOR   START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_EVENTO_CLINICO START WITH 100 INCREMENT BY 1;

-- ─── 2. Sequences das 11 tabelas .NET-owned nascidas na V9 ───────────────────
-- SEQ_LEITURA_TEMP / SEQ_ALERTA_TEMP são abreviadas de propósito — nomes
-- literais de LeituraTemperaturaConfiguration.cs / AlertaTemperaturaConfiguration.cs.
CREATE SEQUENCE SEQ_MEDICAMENTO     START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_NOTIFICACAO     START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DISPOSITIVO_IOT START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_LEITURA_TEMP    START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ALERTA_TEMP     START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TRIAGEM_LUNA    START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_EXAME           START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_VACINA          START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PRESCRICAO      START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DOCUMENTO       START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CONSULTA        START WITH 100 INCREMENT BY 1;

-- ─── 3. Conversão IDENTITY → DEFAULT sequence (tabelas da V1) ────────────────
ALTER TABLE CLINICA        ALTER COLUMN ID_CLINICA      DROP IDENTITY;
ALTER TABLE CLINICA        ALTER COLUMN ID_CLINICA      SET DEFAULT NEXT VALUE FOR SEQ_CLINICA;

ALTER TABLE ESPECIE        ALTER COLUMN ID_ESPECIE      DROP IDENTITY;
ALTER TABLE ESPECIE        ALTER COLUMN ID_ESPECIE      SET DEFAULT NEXT VALUE FOR SEQ_ESPECIE;

ALTER TABLE TIPO_EVENTO    ALTER COLUMN ID_TIPO_EVENTO  DROP IDENTITY;
ALTER TABLE TIPO_EVENTO    ALTER COLUMN ID_TIPO_EVENTO  SET DEFAULT NEXT VALUE FOR SEQ_TIPO_EVENTO;

ALTER TABLE RACA           ALTER COLUMN ID_RACA         DROP IDENTITY;
ALTER TABLE RACA           ALTER COLUMN ID_RACA         SET DEFAULT NEXT VALUE FOR SEQ_RACA;

ALTER TABLE VETERINARIO    ALTER COLUMN ID_VETERINARIO  DROP IDENTITY;
ALTER TABLE VETERINARIO    ALTER COLUMN ID_VETERINARIO  SET DEFAULT NEXT VALUE FOR SEQ_VETERINARIO;

ALTER TABLE TUTOR          ALTER COLUMN ID_TUTOR        DROP IDENTITY;
ALTER TABLE TUTOR          ALTER COLUMN ID_TUTOR        SET DEFAULT NEXT VALUE FOR SEQ_TUTOR;

ALTER TABLE PET            ALTER COLUMN ID_PET          DROP IDENTITY;
ALTER TABLE PET            ALTER COLUMN ID_PET          SET DEFAULT NEXT VALUE FOR SEQ_PET;

ALTER TABLE INVITE_TUTOR   ALTER COLUMN ID_INVITE       DROP IDENTITY;
ALTER TABLE INVITE_TUTOR   ALTER COLUMN ID_INVITE       SET DEFAULT NEXT VALUE FOR SEQ_INVITE_TUTOR;

ALTER TABLE EVENTO_CLINICO ALTER COLUMN ID_EVENTO       DROP IDENTITY;
ALTER TABLE EVENTO_CLINICO ALTER COLUMN ID_EVENTO       SET DEFAULT NEXT VALUE FOR SEQ_EVENTO_CLINICO;

-- ─── 4. Conversão IDENTITY → DEFAULT sequence (tabelas da V9) ────────────────
ALTER TABLE MEDICAMENTO         ALTER COLUMN ID_MEDICAMENTO DROP IDENTITY;
ALTER TABLE MEDICAMENTO         ALTER COLUMN ID_MEDICAMENTO SET DEFAULT NEXT VALUE FOR SEQ_MEDICAMENTO;

ALTER TABLE NOTIFICACAO         ALTER COLUMN ID_NOTIFICACAO DROP IDENTITY;
ALTER TABLE NOTIFICACAO         ALTER COLUMN ID_NOTIFICACAO SET DEFAULT NEXT VALUE FOR SEQ_NOTIFICACAO;

ALTER TABLE DISPOSITIVO_IOT     ALTER COLUMN ID_DISPOSITIVO DROP IDENTITY;
ALTER TABLE DISPOSITIVO_IOT     ALTER COLUMN ID_DISPOSITIVO SET DEFAULT NEXT VALUE FOR SEQ_DISPOSITIVO_IOT;

ALTER TABLE LEITURA_TEMPERATURA ALTER COLUMN ID_LEITURA     DROP IDENTITY;
ALTER TABLE LEITURA_TEMPERATURA ALTER COLUMN ID_LEITURA     SET DEFAULT NEXT VALUE FOR SEQ_LEITURA_TEMP;

ALTER TABLE ALERTA_TEMPERATURA  ALTER COLUMN ID_ALERTA      DROP IDENTITY;
ALTER TABLE ALERTA_TEMPERATURA  ALTER COLUMN ID_ALERTA      SET DEFAULT NEXT VALUE FOR SEQ_ALERTA_TEMP;

ALTER TABLE TRIAGEM_LUNA        ALTER COLUMN ID_TRIAGEM     DROP IDENTITY;
ALTER TABLE TRIAGEM_LUNA        ALTER COLUMN ID_TRIAGEM     SET DEFAULT NEXT VALUE FOR SEQ_TRIAGEM_LUNA;

ALTER TABLE EXAME               ALTER COLUMN ID_EXAME       DROP IDENTITY;
ALTER TABLE EXAME               ALTER COLUMN ID_EXAME       SET DEFAULT NEXT VALUE FOR SEQ_EXAME;

ALTER TABLE VACINA              ALTER COLUMN ID_VACINA      DROP IDENTITY;
ALTER TABLE VACINA              ALTER COLUMN ID_VACINA      SET DEFAULT NEXT VALUE FOR SEQ_VACINA;

ALTER TABLE PRESCRICAO          ALTER COLUMN ID_PRESCRICAO  DROP IDENTITY;
ALTER TABLE PRESCRICAO          ALTER COLUMN ID_PRESCRICAO  SET DEFAULT NEXT VALUE FOR SEQ_PRESCRICAO;

ALTER TABLE DOCUMENTO           ALTER COLUMN ID_DOCUMENTO   DROP IDENTITY;
ALTER TABLE DOCUMENTO           ALTER COLUMN ID_DOCUMENTO   SET DEFAULT NEXT VALUE FOR SEQ_DOCUMENTO;

ALTER TABLE CONSULTA            ALTER COLUMN ID_CONSULTA    DROP IDENTITY;
ALTER TABLE CONSULTA            ALTER COLUMN ID_CONSULTA    SET DEFAULT NEXT VALUE FOR SEQ_CONSULTA;
